### PR TITLE
Models Revision

### PR DESCRIPTION
**Pull request by bew5294**
**Why?**
Updating the models used for the website

**What Changed?**
Removed user model to use default Django user model
Updated .gitignore to ignore all .sqlite3 files
Removed country model to use Django country library in university model instead
Removed old feedback and faculty models

### CODE REVIEW

**Review by kdgromova — COMMENTED** [review]
Looks good! I see that you use Django-countries library, do we need to install it on our local machines to use it? If yes, could you please add a file with dependencies (i.e. requirements.txt)?

**Comment by bew5294** [comment]
@kdgromova The file "install_libraries.txt" lists the commands needed to install the libraries we are using. I could rename it if you think it would be more clear.

**Comment by kdgromova** [comment]
These files are usually called "requirements.txt". I believe that PyCharm IDE will be able to recognize this file and suggest installing packages. Could you please rename it?

**Review by kdgromova — APPROVED** [review]

**Comment by bew5294** [comment]
@kdgromova I added the requirements.txt and the README.md files

**Comment by kdgromova** [comment]
@bew5294 Thank you! Do we need Python 3.7 or Python 3.9 to run the app or any will work? I use 3.9 and it works

**Review by ChrisCee2 — APPROVED** [review]
I haven't tested the code, but it the code looks good to me. The renaming of the models seems to be good and consistent and as long as everyone downloads the new dependencies it should work. Nice!

**Comment by bew5294** [comment]
@kdgromova I'm not sure I am using python 3.9 as well

**Pull request merged**
